### ISSUE TITLE
No ejecuta comandos usando ngrok

### ISSUE THREAD

**Issue by ghost** [an0mal1a/evilShadow#1]
Estuve probándolo con ngrok, cambié la ip y el puerto en el conection.py y el puerto en server.py en las últimas líneas. Cuando lo compilo sin errores y lo ejecuto en windows, en el linux recibe la conexión y en la consola del ngrok sale que se han conectado, pero si ejecuto algo me salta '<* C&C *>:' y no sale por consola el output correspondiente, ya probé con varios comandos pero igual. En el administrador de tareas de windows sigue ejecutándose y el antivirus no lo ha detectado por lo que no es un problema.
No obstante, la compilación la hice sin ofuscación y sin el parámetro --strip ya que daba un error raro y no sabía cómo arreglarlo

**Comment by an0mal1a** [comment]
Ejecuta el comando "targets" deberías ver la sesión con el id: "session 0" 

Si ejecutas session 0 entrarás en la sesión de la víctima 0 y con help deberías ver los comandos existentes. Avísame si necesitas más detalles 

Coméntame si se ha solucionado tu problema para cerrar el issue 😊

**Comment by ghost** [comment]
Ah okay, sí que funcionó, muchas gracias. También estaría bien especificar eso en el readme y tal por si le pasa a alguien más.
Buen repo 👍
